import type { Metadata } from "next"

import { Bangers } from "next/font/google"
import "./globals.css"
import Search from "@/components/Search"

const bangers = Bangers({ subsets: ["latin"], weight: "400" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${bangers.className} bg-black antialiased`}
        suppressHydrationWarning
      >
        <main className="absolute min-h-screen w-full bg-black bg-hero-pattern bg-cover">
          <div className="absolute h-full w-full bg-black/70">
            <div className="mx-auto mt-20 max-w-[1440px] space-y-20 max-lg:p-2">
              <Search />
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  )
}
